---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
# for multi Eureka server: defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: lab-42-subject
words: I,You,He,She,It,They
---
spring:
  profiles: lab-42-verb
words: ran,knew,had,saw,bought
---
spring:
  profiles: lab-42-noun
words: boat,book,vote,seat,backpack,partition,groundhog
---
spring:
  profiles: lab-42-article
words: a,the

---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: run,eat,sit,look,give

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: good,nice,happy,rich

---
spring:
  profiles: noun
words: book,apple,paper,rice
---
spring:
  profiles: lab-52-ribbon-consumer
---
spring:
  profiles: lab-7-client
someones: daisy,lily,lucy,neo    
---
spring:
  profiles: lab-7-feign-consumer
---
spring:
  profiles: lab-7-ribbon-consumer
---
spring:
  profiles: lab-72-ribbon-consumer
