
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
# for multi Eureka server: defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

---
spring:
  profiles: lab-42-noun
words: apple,book,rice,food,mobile

---
spring:
  profiles: lab-42-article
words: a,the

---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: run,eat,sit,look,give

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: good,nice,happy,rich


---
spring:
  profiles: noun
words: book,apple,paper,rice
