---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: lab-42-noun
words: apple,book,rice,food,mobile

---
spring:
  profiles: lab-42-article
words: a,the
