eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: lab-42-noun
words: apple,book,rice,food,mobile
---
spring:
  profiles: lab-42-article
words: a,the
---
spring:
  profiles: primary
server:
  port: 8011
eureka:
  instance:
    hostname: eureka-primary
  client：
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl：
      defaultZone：http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/     
---
spring:
  profiles: secondary
server:
  port: 8012
eureka:
  instance:
    hostname: eureka-secondary
  client：
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl：
      defaultZone：http://eureka-secondary:8013/eureka/,http://eureka-tertiary:8011/eureka/
---
spring:
  profiles: tertiary
server:
  port: 8013
eureka:
  instance:
    hostname: eureka-tertiary
  client：
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl：
      defaultZone：http://eureka-secondary:8011/eureka/,http://eureka-tertiary:8012/eureka/  
