---
eureka:
  client:
    serviceUrl:
#for single Eureka server:
#      defaultZone: http://localhost:8010/eureka/
# for multi Eureka server: 
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: subject
words: I,You,He,She,It
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
---
spring:
  profiles: article
words: a,the
---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
---
spring:
  profiles: lab-7-client
someones: daisy,lily,lucy,neo
---
spring:
  profiles: primary
eureka:
  instance:
    hostname: eureka-primary
  client: 
    registerWithEureka: false
    fetchRegistry: false           
    serviceUrl:
#需要设置注册地址 defaultZone 的值为另外两个Eureka server     
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/      
